apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books-api
spec:
  type: ClusterIP
  selector:
    app: books-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000