apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api-deployment
  labels:
    app: books-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
      - name: books-api
        image: adrianol1/books-api:v11
        ports:
        - containerPort: 8000